### ISSUE TITLE
Plugin marks all lines as uncovered

### ISSUE THREAD

**Issue by richardasaurus** [perimosocordiae/PyCover#3]
What could be the reason for this?
`.coverage` and `coverage.xml` files are present in the project root.

I've tried this on two different machines with the same result. Here are my settings:
```
{
"python": "/Users/richardodwyer/.virtualenvs/all/bin/python",
"onload": false
}
```

And a screenshot:
![screen shot 2015-02-19 at 10 30 46](https://cloud.githubusercontent.com/assets/2279659/6265142/b8868200-b822-11e4-9ab4-dfc49fe91873.png)

**Comment by richardasaurus** [comment]
The issue was coverage 3.7.1 being installed, after upgrading to 4.0 it works as expected :+1:

**Comment by perimosocordiae** [comment]
With coverage 4.0, all lines are still getting marked? What does the console (ctrl-`) say?

**Comment by richardasaurus** [comment]
@perimosocordiae i get this traceback with `coverage==4.0a5`

```
PyCover: Traceback (most recent call last):
  File "/Users/richard/Library/Application Support/Sublime Text 3/Packages/PyCover/scripts/missing_lines.py", line 16, in <module>
    missing_lines(*sys.argv[1:])
  File "/Users/richard/Library/Application Support/Sublime Text 3/Packages/PyCover/scripts/missing_lines.py", line 9, in missing_lines
    if FnmatchMatcher(cov.omit).match(fname):
  File "/Library/Python/2.7/site-packages/coverage/files.py", line 186, in __init__
    self.pats = pats[:]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by perimosocordiae** [comment]
Thanks for the traceback! I was able to reproduce and fix your issue on my end, and I made a new release for Package Control to pick up: https://github.com/perimosocordiae/PyCover/releases/tag/v1.0.6

Let me know if this fixes the plugin for you. (You may have to manually toggle the update from Package Control.)
